// <auto-generated/>
using KiotaEvents.Client.Events.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaEvents.Client.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaEvents.Client.events.item collection</summary>
        /// <param name="position">Get events by start date.</param>
        /// <returns>A <see cref="global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder"/></returns>
        public global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder this[DateOnly position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("start%2Ddate", position);
                return new global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KiotaEvents.Client.events.item collection</summary>
        /// <param name="position">Get events by start date.</param>
        /// <returns>A <see cref="global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("start%2Ddate", position);
                return new global::KiotaEvents.Client.Events.Item.StartDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaEvents.Client.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaEvents.Client.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events", rawUrl)
        {
        }
    }
}
